import type { Metadata } from "next";
import Link from "next/link";

import { ArticleProgress } from "@/components/guides/article-progress";
import { GuideCopyBlock } from "@/components/guides/guide-copy-block";
import { GuidesShell } from "@/components/guides/guides-shell";

import "../guides.css";

const title = "How to generate buyer enquiries with a genuinely curated property list";
const description = "Build a useful local property list around a buyer constraint, explain what makes it different from a portal search, and test the Meta lead path honestly.";
const canonical = "/guides/custom-list-facebook-ad-buyer-leads";

export const metadata: Metadata = { title, description, alternates: { canonical }, openGraph: { type: "article", title, description, url: canonical }, twitter: { card: "summary", title, description } };
const articleSchema = { "@context": "https://schema.org", "@type": "Article", headline: title, description, datePublished: "2026-07-24", dateModified: "2026-09-07", author: { "@type": "Organization", name: "Blockwise" }, publisher: { "@type": "Organization", name: "Blockwise", url: "https://blockwise.sale" }, mainEntityOfPage: `https://blockwise.sale${canonical}` };

const faqItems = [
  ["What makes a custom list more useful than a portal search?", "Curate around a real brief, add context a portal filter does not provide, show trade-offs and update it when the source changes. Do not call a lightly filtered portal results page exclusive."],
  ["Do I need Meta’s Housing Special Ad Category?", "Check the current Meta requirements for the account country and markets reached. Special Ad Category rules may apply to housing-related ads, particularly when based in or reaching the US, Canada or Europe. Australian domestic campaigns are not a universal one-radius case; nondiscrimination always applies."],
  ["Can I target a particular neighbourhood or postcode?", "Use only location controls currently available for your account and market. Do not promise postcode-level delivery or assume a fixed radius. Check the platform settings before publishing."],
  ["How should I judge a small list or a small budget?", "Do not invent a minimum property count or promise leads from a fixed budget. Pause when the list is too thin, document the observed volume and economics, then revise one meaningful input at a time."],
];

const formCopy = "Full name; email; mobile (optional, only if phone contact is explained); What are you hoping to find? [short answer]; Optional: Yes, send me occasional matching property updates from [agency]. I can unsubscribe at any time.";
const deliveryCopy = "Thank-you screen: Your [list name] is ready: [link]. It was last checked [date]. This is a curated guide, not a promise that every property is available. Email: Hi [name], here is the list you requested: [link]. I included [why these properties were selected] and noted [trade-offs]. Reply if you want help comparing one. [agency/contact/privacy].";

const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqItems.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };
export default function CustomListAdGuidePage() {
  return <GuidesShell><ArticleProgress/><main id="main-content"><article className="bw-article">
    <header className="bw-article-hero"><div className="bw-article-hero-copy"><div className="bw-article-breadcrumbs"><Link href="/guides">Guides</Link><span aria-hidden>/</span><span>Buyer leads</span></div><p className="bw-guides-label">The curation guide</p><h1>{title}</h1><p className="bw-article-deck">{description}</p><div className="bw-article-byline"><span>Blockwise</span><span>Updated 7 September 2026</span><span>5 minute read</span></div></div></header>
    <div className="bw-article-at-glance"><h2>At a glance</h2><dl><div><dt>Offer</dt><dd>A local list with a useful, stated buyer brief</dd></div><div><dt>Difference</dt><dd>Context and trade-offs beyond a portal filter</dd></div><div><dt>Test</dt><dd>Choose a spend and review window you can afford</dd></div><div><dt>Measure</dt><dd>Contactable enquiries and useful conversations</dd></div><div><dt>Compliance</dt><dd>Location rules, source permissions and consent</dd></div></dl></div>
    <div className="bw-article-body"><aside className="bw-article-toc" aria-label="On this page"><strong>On this page</strong><a href="#why">Why curate</a><a href="#example">Example</a><a href="#build">Build it</a><a href="#form">Form and delivery</a><a href="#campaign">Campaign</a><a href="#review">Review</a></aside><div className="bw-article-prose">
      <section id="why" className="bw-opening"><p className="bw-drop-intro"><span>A custom list earns attention only when it does more work than a search box.</span> “Homes in [Suburb]” is a portal query. A curated list explains the buyer brief, compares meaningful trade-offs and saves someone the effort of checking every result.</p><p>Choose a constraint people genuinely use — for example, single-level living near a bus route — and add an editorial layer you can substantiate: access notes, likely upkeep, strata information to verify and why each row made the cut. Do not call it exclusive unless it is.</p></section>
      <section id="example" className="bw-text-section"><h2>Concrete synthetic example</h2><p>Brief: “Three-bedroom, single-level homes within an easy trip of [Suburb] shops, with outdoor upkeep described honestly.” This example is fictional; addresses and prices are not real listings.</p><div className="bw-measure-table" role="table" aria-label="Synthetic curated property example"><div role="row" className="bw-measure-head"><span role="columnheader">Property</span><span role="columnheader">Why included</span><span role="columnheader">Check before sharing</span></div><div role="row"><span role="cell">4 Example Street, [Suburb]</span><span role="cell">Single level; small courtyard; near stated bus route</span><span role="cell">Availability, route and upkeep (fictional)</span></div><div role="row"><span role="cell">Unit 2, Sample Walk, [Suburb]</span><span role="cell">Three bedrooms; lift access noted in source</span><span role="cell">Strata costs, lift operation and current status (fictional)</span></div><div role="row"><span role="cell">9 Placeholder Road, [Suburb]</span><span role="cell">Larger yard; suits a different upkeep preference</span><span role="cell">Garden condition and price (fictional)</span></div></div><p>That is curation: explain selection and the downside. A portal search alone does not supply that judgement.</p><a href="/guides/resources/custom-list-facebook-ad-buyer-leads/curated-list-template.csv" download>Download the curated-list template</a></section>
      <section id="build" className="bw-list-section"><div className="bw-section-heading"><span>Build sequence</span><h2>Make the promise testable.</h2></div><div className="bw-list-grid"><div className="bw-list-item"><b>1</b><div><h3>Write the brief</h3><p>Location context, price or finance boundary, property type and one lifestyle constraint.</p><span>Use plain terms people recognise</span></div></div><div className="bw-list-item"><b>2</b><div><h3>Source with permission</h3><p>Confirm listing data and every image can be displayed in this resource and ad.</p><span>Keep source and checked date in your tracker</span></div></div><div className="bw-list-item"><b>3</b><div><h3>Add human context</h3><p>Explain why each property fits and what a buyer should verify.</p><span>Include trade-offs, not just highlights</span></div></div><div className="bw-list-item"><b>4</b><div><h3>Keep the link alive</h3><p>Test mobile loading, availability, enquiry path and removal process.</p><span>Never promise a property that is gone</span></div></div></div></section>
      <section id="form" className="bw-creative-section"><div className="bw-section-heading"><span>Form and delivery</span><h2>Say what you collect and what arrives.</h2></div><GuideCopyBlock title="Lead-form copy" text={formCopy}/><GuideCopyBlock title="Thank-you and delivery copy" text={deliveryCopy}/><div className="bw-source-checklist"><h3>Link and delivery checklist</h3><ul><li>Every property row has a source, checked date and permission note.</li><li>The form privacy link works on mobile.</li><li>The thank-you button opens the actual curated list.</li><li>Remove stale properties and update the last-checked date.</li><li>Explain phone purpose before requesting a mobile number.</li><li>Keep optional marketing consent separate from delivery.</li></ul></div><a href="/guides/resources/custom-list-facebook-ad-buyer-leads/form-delivery-checklist.txt" download>Download the form and delivery checklist</a></section>
      <section id="campaign" className="bw-campaign-section"><div className="bw-section-heading"><span>Meta test</span><h2>Give the platform a clean brief and room to show evidence.</h2></div><div className="bw-campaign-settings"><dl><div><dt>Objective</dt><dd>Leads</dd></div><div><dt>Offer</dt><dd>Named curated list; do not imply exclusivity without proof</dd></div><div><dt>Form</dt><dd>Short, higher-intent review step where available</dd></div><div><dt>Budget</dt><dd>Choose a spend that fits your economics; no fixed budget guarantees data</dd></div><div><dt>Location</dt><dd>Use current account and market controls; do not assume an Australian universal radius</dd></div></dl></div><p>Meta says delivery may stabilise around 50 results in a week after the last significant edit, but that is a platform learning reference, not a three-day rule or a guaranteed outcome. Review observed volume, contactability and cost, then make one meaningful change rather than tinkering daily.</p><p>Where an ad is based in or reaches the US, Canada or Europe, check the current Special Ad Category rules. For an Australian domestic campaign, do not assume a housing-radius requirement without checking the account. Nondiscrimination and truthful presentation apply regardless.</p><GuideCopyBlock title="Primary text specimen" text="A short list for a specific brief: [feature] homes near [location context], with the trade-offs explained. Request the current guide and check which options are still available."/><a href="/guides/resources/custom-list-facebook-ad-buyer-leads/copy-specimens.txt" download>Download copy specimens</a></section>
      <section id="review" className="bw-measure-section"><div className="bw-section-heading"><span>Read the evidence</span><h2>Higher intent is a review input, not a guarantee.</h2></div><p>Track spend, form submissions, valid contact details, replies, useful conversations and appointments. A higher-intent form can add a review step, but it does not guarantee contactability or buyer intent. If a lead replies, answer the question and follow their channel preference. If the list is stale or the source permission changes, pause the ad before chasing a cheaper lead.</p><div className="bw-contrast-row"><div><span>Continue</span><strong>The list remains accurate, useful and economically supportable.</strong></div><div><span>Revise or stop</span><strong>The source, promise, link or lead quality cannot be maintained.</strong></div></div></section>
      <section className="bw-faq-section"><div className="bw-section-heading"><span>Questions</span><h2>The practical details.</h2></div>{faqItems.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
      <footer className="bw-article-sources"><h2>Sources</h2><ol><li><a href="https://developers.facebook.com/docs/marketing-api/audiences/special-ad-category/" target="_blank" rel="noreferrer">Meta Special Ad Category guidance</a></li><li><a href="https://www.facebook.com/business/help/112167992830700" target="_blank" rel="noreferrer">Meta delivery and learning help</a></li><li><a href="https://www.acma.gov.au/avoid-sending-spam" target="_blank" rel="noreferrer">ACMA: Avoid sending spam</a></li></ol><p className="bw-last-reviewed">Updated 7 September 2026</p></footer>
    </div></div>
  </article></main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/></GuidesShell>;
}
