// AUTO-GENERATED by scripts/adstudio-build-extracted-meta-templates.py. Do not edit by hand.
// Slice contains 10 of 330 extracted Meta ad candidate images.

export const EXTRACTED_META_TEMPLATE_TOTAL = 330 as const;
export const EXTRACTED_META_TEMPLATE_SLICE_SIZE = 10 as const;

export const EXTRACTED_META_TEMPLATE_DESCRIPTORS = [
  {
    "id": "meta_002",
    "name": "Feed 002 - Buying or Selling Agent Ad",
    "sourceFile": "01_feed_4x5_best/meta_002.png",
    "originalFile": "portrait_4x5/template_002.png",
    "aspectBucket": "portrait_4x5",
    "nativeFormat": "4:5",
    "placement": "Meta feed single-image ads",
    "useLevel": "direct_best",
    "imageSize": {
      "w": 566,
      "h": 731
    },
    "palette": [
      "#8B8176",
      "#FFFFFF",
      "#E7B24B",
      "#0B1720",
      "#D4D5D4",
      "#C0BDB9"
    ],
    "photoRects": [
      {
        "x": 0.02,
        "y": 0.02,
        "w": 0.96,
        "h": 0.39
      },
      {
        "x": 0.69,
        "y": 0.66,
        "w": 0.24,
        "h": 0.27
      }
    ],
    "panelRect": {
      "x": 0.08,
      "y": 0.47,
      "w": 0.84,
      "h": 0.3
    },
    "kind": "agent",
    "goal": "seller_leads",
    "offerId": "prelisting_timeline",
    "imageBriefId": "IMG-AGENT-INTRO",
    "promptHint": "Rebuild the source agent-led ad with a portrait slot, service bullets, signature/name block, and compact contact CTA. Source image: 01_feed_4x5_best/meta_002.png; original extraction: portrait_4x5/template_002.png.",
    "sampleCopy": {
      "headline": "Buying or selling in Bicton?",
      "primaryText": "Work with Priya Nair for clear local advice before your next move.",
      "description": "Agent-led property help for local owners.",
      "cta": "Start planning"
    },
    "sampleStyle": {
      "propertyAge": "apartment_townhouse",
      "priceFeel": "investor_rental",
      "visualStyle": "organic_agent_post",
      "people": "buyer_activity",
      "copyDensity": "small_badge",
      "tone": "simple_super_premium",
      "sampleSuburb": "Bicton",
      "agencyName": "Northbank Realty",
      "agentName": "Priya Nair",
      "address": "12 Bicton Road, Bicton",
      "propertyDetail": "architect-designed residence",
      "resultDetail": "local context sample"
    },
    "evidenceScore": 72
  },
  {
    "id": "meta_021",
    "name": "Feed 021 - New On The Market Collage",
    "sourceFile": "01_feed_4x5_best/meta_021.png",
    "originalFile": "portrait_4x5/template_021.png",
    "aspectBucket": "portrait_4x5",
    "nativeFormat": "4:5",
    "placement": "Meta feed single-image ads",
    "useLevel": "direct_best",
    "imageSize": {
      "w": 511,
      "h": 636
    },
    "palette": [
      "#CCBCAD",
      "#0B1720",
      "#9D8671",
      "#FFFFFF",
      "#FBF7F4",
      "#F7F4F1",
      "#FEFCFB"
    ],
    "photoRects": [
      {
        "x": 0.43,
        "y": 0.58,
        "w": 0.45,
        "h": 0.32
      },
      {
        "x": 0.12,
        "y": 0.58,
        "w": 0.26,
        "h": 0.32
      },
      {
        "x": 0.34,
        "y": 0.66,
        "w": 0.19,
        "h": 0.18
      }
    ],
    "panelRect": {
      "x": 0.08,
      "y": 0.12,
      "w": 0.84,
      "h": 0.42
    },
    "kind": "listing",
    "goal": "seller_leads",
    "offerId": "recent_sales_report",
    "imageBriefId": "IMG-JUST-LISTED",
    "promptHint": "Rebuild the source listing ad as editable property-photo slots, headline, feature chips, price or address row, and a clear CTA. Source image: 01_feed_4x5_best/meta_021.png; original extraction: portrait_4x5/template_021.png.",
    "sampleCopy": {
      "headline": "New on the market in Fremantle",
      "primaryText": "A fresh local listing with the features owners and buyers are watching.",
      "description": "Fresh listing context for local owners.",
      "cta": "View listing"
    },
    "sampleStyle": {
      "propertyAge": "renovated_character",
      "priceFeel": "affordable_entry",
      "visualStyle": "guide_or_report_mockup",
      "people": "none",
      "copyDensity": "headline_overlay",
      "tone": "urgent_listing",
      "sampleSuburb": "Fremantle",
      "agencyName": "Bluestone Residential",
      "agentName": "Leo Romano",
      "address": "31 Fremantle Road, Fremantle",
      "propertyDetail": "renovated family home",
      "resultDetail": "local context sample"
    },
    "evidenceScore": 74
  },
  {
    "id": "meta_040",
    "name": "Square 040 - Luxury Apartments",
    "sourceFile": "03_square_feed_carousel_marketplace/meta_040.png",
    "originalFile": "square_1x1/template_040.png",
    "aspectBucket": "square_1x1",
    "nativeFormat": "1:1",
    "placement": "Square feed, carousel, Marketplace-style ads",
    "useLevel": "direct_good",
    "imageSize": {
      "w": 561,
      "h": 561
    },
    "palette": [
      "#593D34",
      "#FFFFFF",
      "#0B1720",
      "#F0F5F8",
      "#FDFDFD",
      "#63443A"
    ],
    "photoRects": [
      {
        "x": 0.05,
        "y": 0.42,
        "w": 0.9,
        "h": 0.39
      }
    ],
    "panelRect": {
      "x": 0.07,
      "y": 0.07,
      "w": 0.86,
      "h": 0.35
    },
    "kind": "development",
    "goal": "seller_leads",
    "offerId": "recent_sales_report",
    "imageBriefId": "IMG-DEV-HERO",
    "promptHint": "Rebuild the source development ad with architectural image slots, feature chips, release badge, and enquiry CTA. Source image: 03_square_feed_carousel_marketplace/meta_040.png; original extraction: square_1x1/template_040.png.",
    "sampleCopy": {
      "headline": "Luxury apartments in North Perth",
      "primaryText": "Showcase premium amenities, hero imagery, and a direct enquiry path.",
      "description": "Premium apartment campaign creative.",
      "cta": "View release"
    },
    "sampleStyle": {
      "propertyAge": "luxury_architectural",
      "priceFeel": "premium_coastal",
      "visualStyle": "data_card",
      "people": "agent_portrait",
      "copyDensity": "full_sales_poster",
      "tone": "practical_local",
      "sampleSuburb": "North Perth",
      "agencyName": "Harbour Lane Property",
      "agentName": "Mia Hart",
      "address": "50 North Perth Road, North Perth",
      "propertyDetail": "character home",
      "resultDetail": "local context sample"
    },
    "evidenceScore": 76
  },
  {
    "id": "meta_044",
    "name": "Feed 044 - Open House Detail Card",
    "sourceFile": "01_feed_4x5_best/meta_044.png",
    "originalFile": "portrait_4x5/template_044.png",
    "aspectBucket": "portrait_4x5",
    "nativeFormat": "4:5",
    "placement": "Meta feed single-image ads",
    "useLevel": "direct_best",
    "imageSize": {
      "w": 561,
      "h": 701
    },
    "palette": [
      "#FFFFFF",
      "#0B1720",
      "#E7B24B",
      "#1B1C1C",
      "#CDCCC8",
      "#252626"
    ],
    "photoRects": [
      {
        "x": 0.02,
        "y": 0.02,
        "w": 0.96,
        "h": 0.5
      },
      {
        "x": 0.45,
        "y": 0.55,
        "w": 0.47,
        "h": 0.25
      }
    ],
    "panelRect": {
      "x": 0.08,
      "y": 0.56,
      "w": 0.34,
      "h": 0.26
    },
    "kind": "open_home",
    "goal": "open_home_followup",
    "offerId": "open_home_followup",
    "imageBriefId": "IMG-OPEN-HOME",
    "promptHint": "Rebuild the source open-home ad with date/time, property photo, address strip, and inspection CTA as editable layers. Source image: 01_feed_4x5_best/meta_044.png; original extraction: portrait_4x5/template_044.png.",
    "sampleCopy": {
      "headline": "Open house this Saturday",
      "primaryText": "Inspect the property, see the key spaces, and plan your follow-up questions.",
      "description": "Open-home details with a clear CTA.",
      "cta": "Plan your visit"
    },
    "sampleStyle": {
      "propertyAge": "older_affordable",
      "priceFeel": "mid_market_family",
      "visualStyle": "property_photo_first",
      "people": "buyer_activity",
      "copyDensity": "minimal_no_overlay",
      "tone": "quiet_editorial",
      "sampleSuburb": "Joondalup",
      "agencyName": "Jarrah Property",
      "agentName": "Grace Okafor",
      "address": "54 Joondalup Road, Joondalup",
      "propertyDetail": "modern family home",
      "resultDetail": "local context sample"
    },
    "evidenceScore": 80
  },
  {
    "id": "meta_055",
    "name": "Feed 055 - Editorial Just Sold",
    "sourceFile": "01_feed_4x5_best/meta_055.png",
    "originalFile": "portrait_4x5/template_055.png",
    "aspectBucket": "portrait_4x5",
    "nativeFormat": "4:5",
    "placement": "Meta feed single-image ads",
    "useLevel": "direct_best",
    "imageSize": {
      "w": 686,
      "h": 851
    },
    "palette": [
      "#8E8C6B",
      "#FFFFFF",
      "#0B1720",
      "#FAF7F2",
      "#F0EBE5",
      "#DBE0E7"
    ],
    "photoRects": [
      {
        "x": 0.05,
        "y": 0.27,
        "w": 0.9,
        "h": 0.39
      },
      {
        "x": 0.17,
        "y": 0.59,
        "w": 0.18,
        "h": 0.18
      }
    ],
    "panelRect": {
      "x": 0.08,
      "y": 0.07,
      "w": 0.84,
      "h": 0.2
    },
    "kind": "sold",
    "goal": "seller_leads",
    "offerId": "recent_sales_report",
    "imageBriefId": "IMG-JUST-SOLD",
    "promptHint": "Rebuild the source sold-result ad with sold badge, property slot, result strip, and compliant local context CTA. Source image: 01_feed_4x5_best/meta_055.png; original extraction: portrait_4x5/template_055.png.",
    "sampleCopy": {
      "headline": "Just sold in North Perth",
      "primaryText": "Use the latest local sale as context before you decide your next property step.",
      "description": "Recent sale context without over-claiming.",
      "cta": "Get local context"
    },
    "sampleStyle": {
      "propertyAge": "luxury_architectural",
      "priceFeel": "premium_coastal",
      "visualStyle": "data_card",
      "people": "owner_lifestyle",
      "copyDensity": "full_sales_poster",
      "tone": "practical_local",
      "sampleSuburb": "North Perth",
      "agencyName": "Coastal & Co Realty",
      "agentName": "Elliot Marsh",
      "address": "65 North Perth Road, North Perth",
      "propertyDetail": "coastal apartment",
      "resultDetail": "local context sample"
    },
    "evidenceScore": 74
  },
  {
    "id": "meta_094",
    "name": "Square 094 - Modern Home For Sale",
    "sourceFile": "03_square_feed_carousel_marketplace/meta_094.png",
    "originalFile": "square_1x1/template_094.png",
    "aspectBucket": "square_1x1",
    "nativeFormat": "1:1",
    "placement": "Square feed, carousel, Marketplace-style ads",
    "useLevel": "direct_good",
    "imageSize": {
      "w": 561,
      "h": 566
    },
    "palette": [
      "#45464F",
      "#FFFFFF",
      "#51413C",
      "#0B1720",
      "#FDFCFC",
      "#82858A",
      "#B19F8F"
    ],
    "photoRects": [
      {
        "x": 0.0,
        "y": 0.31,
        "w": 1.0,
        "h": 0.34
      }
    ],
    "panelRect": {
      "x": 0.08,
      "y": 0.07,
      "w": 0.84,
      "h": 0.24
    },
    "kind": "listing",
    "goal": "seller_leads",
    "offerId": "recent_sales_report",
    "imageBriefId": "IMG-JUST-LISTED",
    "promptHint": "Rebuild the source listing ad as editable property-photo slots, headline, feature chips, price or address row, and a clear CTA. Source image: 03_square_feed_carousel_marketplace/meta_094.png; original extraction: square_1x1/template_094.png.",
    "sampleCopy": {
      "headline": "Modern home for sale",
      "primaryText": "Lead with the hero property photo, price guide, and a simple enquiry CTA.",
      "description": "Square feed listing ad.",
      "cta": "View details"
    },
    "sampleStyle": {
      "propertyAge": "older_affordable",
      "priceFeel": "mid_market_family",
      "visualStyle": "property_photo_first",
      "people": "agent_portrait",
      "copyDensity": "minimal_no_overlay",
      "tone": "quiet_editorial",
      "sampleSuburb": "Cottesloe",
      "agencyName": "Foreshore & Park",
      "agentName": "Sarah Chen",
      "address": "104 Cottesloe Road, Cottesloe",
      "propertyDetail": "low-maintenance villa",
      "resultDetail": "local context sample"
    },
    "evidenceScore": 79
  },
  {
    "id": "meta_142",
    "name": "Square 142 - Agent Just Sold",
    "sourceFile": "03_square_feed_carousel_marketplace/meta_142.png",
    "originalFile": "square_1x1/template_142.png",
    "aspectBucket": "square_1x1",
    "nativeFormat": "1:1",
    "placement": "Square feed, carousel, Marketplace-style ads",
    "useLevel": "direct_good",
    "imageSize": {
      "w": 601,
      "h": 601
    },
    "palette": [
      "#043927",
      "#FFFFFF",
      "#033927",
      "#0B1720",
      "#FAF9F7",
      "#909A74",
      "#BFB29A"
    ],
    "photoRects": [
      {
        "x": 0.0,
        "y": 0.19,
        "w": 1.0,
        "h": 0.62
      },
      {
        "x": 0.0,
        "y": 0.52,
        "w": 0.31,
        "h": 0.4
      }
    ],
    "panelRect": {
      "x": 0.07,
      "y": 0.05,
      "w": 0.86,
      "h": 0.15
    },
    "kind": "sold",
    "goal": "seller_leads",
    "offerId": "recent_sales_report",
    "imageBriefId": "IMG-JUST-SOLD",
    "promptHint": "Rebuild the source sold-result ad with sold badge, property slot, result strip, and compliant local context CTA. Source image: 03_square_feed_carousel_marketplace/meta_142.png; original extraction: square_1x1/template_142.png.",
    "sampleCopy": {
      "headline": "Just sold near Mount Lawley",
      "primaryText": "A recent local result can help owners read current buyer response.",
      "description": "Agent-led sold proof for Meta feed.",
      "cta": "See recent sales"
    },
    "sampleStyle": {
      "propertyAge": "apartment_townhouse",
      "priceFeel": "investor_rental",
      "visualStyle": "organic_agent_post",
      "people": "agent_portrait",
      "copyDensity": "small_badge",
      "tone": "simple_super_premium",
      "sampleSuburb": "Mount Lawley",
      "agencyName": "Foreshore & Park",
      "agentName": "Sarah Chen",
      "address": "152 Mount Lawley Road, Mount Lawley",
      "propertyDetail": "low-maintenance villa",
      "resultDetail": "local context sample"
    },
    "evidenceScore": 76
  },
  {
    "id": "meta_245",
    "name": "Story 245 - Looking For An Agent",
    "sourceFile": "02_stories_reels_9x16/meta_245.png",
    "originalFile": "portrait_9x16/template_245.png",
    "aspectBucket": "portrait_9x16",
    "nativeFormat": "9:16",
    "placement": "Stories and Reels-style full-screen ads",
    "useLevel": "direct_best",
    "imageSize": {
      "w": 506,
      "h": 881
    },
    "palette": [
      "#4A3E3D",
      "#FFFFFF",
      "#806252",
      "#0B1720",
      "#F6F4F3",
      "#B3917B"
    ],
    "photoRects": [
      {
        "x": 0.43,
        "y": 0.25,
        "w": 0.47,
        "h": 0.58
      }
    ],
    "panelRect": {
      "x": 0.08,
      "y": 0.11,
      "w": 0.84,
      "h": 0.22
    },
    "kind": "agent",
    "goal": "seller_leads",
    "offerId": "prelisting_timeline",
    "imageBriefId": "IMG-AGENT-INTRO",
    "promptHint": "Rebuild the source agent-led ad with a portrait slot, service bullets, signature/name block, and compact contact CTA. Source image: 02_stories_reels_9x16/meta_245.png; original extraction: portrait_9x16/template_245.png.",
    "sampleCopy": {
      "headline": "Looking for a real estate agent?",
      "primaryText": "Leo Romano can help you plan the next property step in Victoria Park.",
      "description": "Vertical agent lead ad.",
      "cta": "Schedule a call"
    },
    "sampleStyle": {
      "propertyAge": "luxury_architectural",
      "priceFeel": "premium_coastal",
      "visualStyle": "data_card",
      "people": "none",
      "copyDensity": "full_sales_poster",
      "tone": "practical_local",
      "sampleSuburb": "Victoria Park",
      "agencyName": "Bluestone Residential",
      "agentName": "Leo Romano",
      "address": "255 Victoria Park Road, Victoria Park",
      "propertyDetail": "renovated family home",
      "resultDetail": "local context sample"
    },
    "evidenceScore": 77
  },
  {
    "id": "meta_259",
    "name": "Story 259 - New Listing Stack",
    "sourceFile": "02_stories_reels_9x16/meta_259.png",
    "originalFile": "portrait_9x16/template_259.png",
    "aspectBucket": "portrait_9x16",
    "nativeFormat": "9:16",
    "placement": "Stories and Reels-style full-screen ads",
    "useLevel": "direct_best",
    "imageSize": {
      "w": 506,
      "h": 886
    },
    "palette": [
      "#5A5C34",
      "#FFFFFF",
      "#0B1720",
      "#000000",
      "#D9D9D8",
      "#B6B6B4"
    ],
    "photoRects": [
      {
        "x": 0.0,
        "y": 0.29,
        "w": 1.0,
        "h": 0.27
      },
      {
        "x": 0.0,
        "y": 0.56,
        "w": 1.0,
        "h": 0.31
      },
      {
        "x": 0.72,
        "y": 0.77,
        "w": 0.24,
        "h": 0.18
      }
    ],
    "panelRect": {
      "x": 0.08,
      "y": 0.05,
      "w": 0.84,
      "h": 0.23
    },
    "kind": "listing",
    "goal": "seller_leads",
    "offerId": "recent_sales_report",
    "imageBriefId": "IMG-JUST-LISTED",
    "promptHint": "Rebuild the source listing ad as editable property-photo slots, headline, feature chips, price or address row, and a clear CTA. Source image: 02_stories_reels_9x16/meta_259.png; original extraction: portrait_9x16/template_259.png.",
    "sampleCopy": {
      "headline": "New listing in Cottesloe",
      "primaryText": "Stack hero photos, price, specs, and contact details for a fast story ad.",
      "description": "Story-format listing ad.",
      "cta": "View listing"
    },
    "sampleStyle": {
      "propertyAge": "older_affordable",
      "priceFeel": "mid_market_family",
      "visualStyle": "property_photo_first",
      "people": "owner_lifestyle",
      "copyDensity": "minimal_no_overlay",
      "tone": "quiet_editorial",
      "sampleSuburb": "Cottesloe",
      "agencyName": "Civic Estate Agents",
      "agentName": "Tom Walker",
      "address": "269 Cottesloe Road, Cottesloe",
      "propertyDetail": "investment apartment",
      "resultDetail": "local context sample"
    },
    "evidenceScore": 74
  },
  {
    "id": "meta_317",
    "name": "Story 317 - Open House For Sale",
    "sourceFile": "02_stories_reels_9x16/meta_317.png",
    "originalFile": "portrait_9x16/template_317.png",
    "aspectBucket": "portrait_9x16",
    "nativeFormat": "9:16",
    "placement": "Stories and Reels-style full-screen ads",
    "useLevel": "direct_best",
    "imageSize": {
      "w": 506,
      "h": 876
    },
    "palette": [
      "#8E8A80",
      "#FFFFFF",
      "#E7B24B",
      "#0B1720",
      "#D9E4F3",
      "#EFEFEF",
      "#6B6768"
    ],
    "photoRects": [
      {
        "x": 0.36,
        "y": 0.2,
        "w": 0.64,
        "h": 0.58
      },
      {
        "x": 0.16,
        "y": 0.29,
        "w": 0.25,
        "h": 0.16
      },
      {
        "x": 0.16,
        "y": 0.5,
        "w": 0.25,
        "h": 0.16
      },
      {
        "x": 0.28,
        "y": 0.67,
        "w": 0.25,
        "h": 0.16
      }
    ],
    "panelRect": {
      "x": 0.07,
      "y": 0.07,
      "w": 0.86,
      "h": 0.16
    },
    "kind": "open_home",
    "goal": "open_home_followup",
    "offerId": "open_home_followup",
    "imageBriefId": "IMG-OPEN-HOME",
    "promptHint": "Rebuild the source open-home ad with date/time, property photo, address strip, and inspection CTA as editable layers. Source image: 02_stories_reels_9x16/meta_317.png; original extraction: portrait_9x16/template_317.png.",
    "sampleCopy": {
      "headline": "Open house for sale",
      "primaryText": "Promote the inspection with supporting room previews and key details.",
      "description": "Vertical open-home story ad.",
      "cta": "Plan your visit"
    },
    "sampleStyle": {
      "propertyAge": "apartment_townhouse",
      "priceFeel": "investor_rental",
      "visualStyle": "organic_agent_post",
      "people": "none",
      "copyDensity": "small_badge",
      "tone": "simple_super_premium",
      "sampleSuburb": "Bicton",
      "agencyName": "Bluestone Residential",
      "agentName": "Leo Romano",
      "address": "327 Bicton Road, Bicton",
      "propertyDetail": "renovated family home",
      "resultDetail": "local context sample"
    },
    "evidenceScore": 81
  }
] as const;
