import type { AdStudioFormat, AdStudioGoal, MetaLeadAdPack } from "./types.ts";
import { RAW_ADSTUDIO_GALLERY_TEMPLATES } from "./template-gallery/index.ts";
import { templateDisplaySrc } from "./template-display.ts";

export type AdStudioTemplateImageInput = {
  key: string;
  label: string;
  required: boolean;
  aspect?: "landscape" | "portrait" | "square";
  description: string;
};

export type AdStudioTemplateTextInput = {
  key: string;
  label: string;
  maxLength: number;
  sample: string;
  required: boolean;
};

export type AdStudioTemplateSourceAd = {
  creativeId?: string;
  file?: string;
  contentHash: string;
};

export type AdStudioTemplateClassification = {
  ad_type: string;
  primary_intent: string;
  property_or_agent_focus: string;
};

export type AdStudioTemplateSample = {
  imageSrc: string;
  thumbnailSrc: string;
  alt: string;
  contentHash: string;
  generatedBy: "reference_clone";
};

export type AdStudioTemplateMeta = MetaLeadAdPack & {
  objective: "OUTCOME_LEADS";
  publisherPlatforms: ["facebook", "instagram"];
  facebookPositions: string[];
  instagramPositions: string[];
};

/**
 * The only AdStudio template contract.
 *
 * A template is a safe sample image plus the customer inputs needed to clone
 * it. It contains no second rendering recipe. The sample image is the design.
 */
export type AdStudioTemplate = {
  id: string;
  name: string;
  goal: AdStudioGoal;
  offerId: string;
  source: "builtin";
  status: "approved";
  format: "4:5" | "9:16";
  dimensions: {
    width: 1080;
    height: 1350 | 1920;
  };
  audienceIntent: string;
  category: string;
  tags: string[];
  sample: AdStudioTemplateSample;
  inputs: {
    images: AdStudioTemplateImageInput[];
    text: AdStudioTemplateTextInput[];
  };
  meta: AdStudioTemplateMeta;
  sourceAd: AdStudioTemplateSourceAd;
  classification: AdStudioTemplateClassification;
};

export type AdStudioGalleryTemplate = AdStudioTemplate;

export const AD_STUDIO_TEMPLATES: AdStudioTemplate[] = RAW_ADSTUDIO_GALLERY_TEMPLATES.map(validateGalleryTemplate);
export const RESOLVABLE_AD_STUDIO_TEMPLATES: AdStudioTemplate[] = AD_STUDIO_TEMPLATES.filter(
  (template) => template.status === "approved",
);

export function resolveAdStudioTemplate(templateId: string | undefined): AdStudioTemplate | null {
  if (!templateId) return null;
  return RESOLVABLE_AD_STUDIO_TEMPLATES.find((template) => template.id === templateId) ?? null;
}

export function isBuiltInAdStudioTemplate(templateId: string | undefined): boolean {
  return Boolean(resolveAdStudioTemplate(templateId));
}

export function builtInAdStudioTemplates(): AdStudioTemplate[] {
  return AD_STUDIO_TEMPLATES.map((template) => ({
    ...template,
    sample: {
      ...template.sample,
      thumbnailSrc: templateDisplaySrc(template, "640"),
    },
  }));
}

export function resolvableAdStudioTemplates(): AdStudioTemplate[] {
  return [...RESOLVABLE_AD_STUDIO_TEMPLATES];
}

function validateGalleryTemplate(raw: AdStudioTemplate): AdStudioTemplate {
  const errors: string[] = [];
  const expectedHeight = raw?.format === "4:5" ? 1350 : raw?.format === "9:16" ? 1920 : null;

  if (!raw?.id) errors.push("id is required");
  if (!raw?.name) errors.push("name is required");
  if (raw?.status !== "approved") errors.push("status must be approved");
  if (raw?.source !== "builtin") errors.push("source must be builtin");
  if (raw?.dimensions?.width !== 1080 || raw?.dimensions?.height !== expectedHeight) {
    errors.push("dimensions do not match format");
  }
  if (!raw?.sample?.thumbnailSrc || !raw?.sample?.imageSrc) errors.push("sample image paths are required");
  if (raw?.sample?.generatedBy !== "reference_clone") errors.push("sample must be generated by reference clone");
  if (!isSha256(raw?.sourceAd?.contentHash)) errors.push("sourceAd.contentHash must be a SHA-256 hash");
  if (!isSha256(raw?.sample?.contentHash)) errors.push("sample.contentHash must be a SHA-256 hash");
  if (raw?.sourceAd?.contentHash === raw?.sample?.contentHash) errors.push("gallery sample must not be the source ad");
  if (!raw?.sourceAd?.creativeId && !raw?.sourceAd?.file) errors.push("sourceAd provenance is required");
  if (!Array.isArray(raw?.inputs?.images) || raw.inputs.images.length === 0) errors.push("at least one image input is required");
  if (!raw?.inputs?.images?.some((input) => input.required)) errors.push("at least one image input must be required");
  validateUniqueKeys(raw?.inputs?.images ?? [], "image", errors);
  validateUniqueKeys(raw?.inputs?.text ?? [], "text", errors);
  for (const field of raw?.inputs?.text ?? []) {
    if (!field.label?.trim() || !field.sample?.trim() || !Number.isInteger(field.maxLength) || field.maxLength < 1) {
      errors.push(`text input ${field.key || "<unknown>"} is invalid`);
    }
  }
  if (raw?.meta?.platform !== "meta") errors.push("meta platform must be meta");
  if (raw?.meta?.objective !== "OUTCOME_LEADS") errors.push("meta objective must be OUTCOME_LEADS");
  if (raw?.meta?.specialAdCategory !== "housing") errors.push("meta special ad category must be housing");

  if (errors.length) {
    throw new Error(`Invalid AdStudio gallery template ${raw?.id ?? "<unknown>"}: ${errors.join("; ")}`);
  }

  return raw;
}

function validateUniqueKeys(items: Array<{ key: string; label: string }>, kind: string, errors: string[]): void {
  const keys = new Set<string>();
  for (const item of items) {
    const key = item.key?.trim();
    if (!key || !item.label?.trim()) {
      errors.push(`${kind} input key and label are required`);
      continue;
    }
    if (keys.has(key)) errors.push(`duplicate ${kind} input key: ${key}`);
    keys.add(key);
  }
}

function isSha256(value: unknown): value is string {
  return typeof value === "string" && /^[a-f0-9]{64}$/iu.test(value);
}

export type { AdStudioFormat };
