#!/usr/bin/env bash
set -euo pipefail
fail() { echo "ad-db first-fill preflight: $" >&2; exit 1; }
required() { [[ -n "${!1:-}" ]] || fail "missing required environment key: $1"; }
validate_vault_url() { local url=$1 host; [[ "$url" =~ ^https?://[^/:]+ ]] || fail "HERMES_PROVIDER_VAULT_URL must be an http(s) URL"; host=${url#*://}; host=${host%%/*}; host=${host%%:*}; [[ "$host" != *.supabase.co && "$host" != *.supabase.com ]] || fail "HERMES_PROVIDER_VAULT_URL must target the self-hosted vault"; }
validate_billing() { local cap=${HERMES_APIFY_ACCOUNT_HARD_CAP_USD:-} run=${HERMES_APIFY_FIRST_FILL_MAX_TOTAL_CHARGE_USD:-}; [[ "$cap" =~ ^[0-9]+([.][0-9]+)?$ && "$run" =~ ^[0-9]+([.][0-9]+)?$ ]] || fail "Apify billing caps must be configured"; awk -v cap="$cap" -v run="$run" 'BEGIN { exit !(cap > 0 && cap <= 19 && run > 0 && run <= cap) }' || fail "Apify billing cap must be positive, at most USD 19, and cover the run cap"; }
validate_environment() { required HERMES_PROVIDER_VAULT_URL; required HERMES_PROVIDER_VAULT_SECRET_KEY; required TOKEN_ENCRYPTION_KEY; required HERMES_SUPABASE_URL; required HERMES_SUPABASE_SECRET_KEY; validate_vault_url "$HERMES_PROVIDER_VAULT_URL"; validate_billing; }
safe_load_required_environment() { local file=$1 key value; [[ -r "$file" ]] || fail "missing readable environment file"; for key in HERMES_PROVIDER_VAULT_URL HERMES_PROVIDER_VAULT_SECRET_KEY TOKEN_ENCRYPTION_KEY HERMES_SUPABASE_URL HERMES_SUPABASE_SECRET_KEY HERMES_APIFY_ACCOUNT_HARD_CAP_USD HERMES_APIFY_FIRST_FILL_MAX_TOTAL_CHARGE_USD; do value=$(awk -F= -v key="$key" '$0 !~ /^[[:space:]]*[#;]/ && $1 == key { if (++n == 1) print substr($0, index($0, "=") + 1); else exit 2 } END { if (!n) exit 1 }' "$file") || fail "missing or duplicate environment key: $key"; value=${value#\"}; value=${value%\"}; value=${value#\'}; value=${value%\'}; [[ -n "$value" ]] || fail "empty environment key: $key"; export "$key=$value"; done; }
preflight() { local root=$1 envfile=$2; [[ -f "$root/hermes/tools/research-runtime/bin/supabase-supervisor.mjs" ]] || fail "missing supervisor"; /usr/bin/node --check "$root/hermes/tools/research-runtime/bin/supabase-supervisor.mjs"; /usr/bin/node "$root/scripts/vps/hermes-ad-db-runtime-imports.mjs"; safe_load_required_environment "$envfile"; validate_environment; }
if [[ ${1:-} == --preflight ]]; then [[ $# -eq 3 ]] || fail "usage: --preflight RELEASE_ROOT ENV_FILE"; preflight "$2" "$3"; exit 0; fi
[[ $# -eq 1 ]] || fail "usage: RELEASE_ROOT"; root=$1; validate_environment
exec env -u HERMES_META_CAPTURE_PROVIDER -u HERMES_META_CAPTURE_ENDPOINT -u HERMES_META_CAPTURE_CLI_PATH -u HERMES_META_BROWSER_EXECUTABLE -u HERMES_REMOTE_BROWSER_CDP_URL -u RESIDENTIAL_PROXY_URL -u HERMES_META_CAPTURE_PROXY_URL HERMES_AD_RADAR_FIRST_FILL_PROVIDER=apify HERMES_AD_RADAR_FIRST_FILL_ONLY=true HERMES_SCRAPINGBEE_ENABLED=false HERMES_META_OFFICIAL_API_ENABLED=false /usr/bin/node "$root/hermes/tools/research-runtime/bin/supabase-supervisor.mjs" --ad-db-worker
