import type { Metadata } from "next";
import Link from "next/link";

import { ArticleProgress } from "@/components/guides/article-progress";
import { GuideCopyBlock } from "@/components/guides/guide-copy-block";
import { GuidesShell } from "@/components/guides/guides-shell";
import { DownsizingEconomicsCalculator } from "./economics-calculator";

import "../guides.css";

const title = "How to test a transparent downsizer campaign for seller intent";
const description = "Offer a genuine list of lower-maintenance homes, then ask whether a buyer also needs to sell. Test the hypothesis honestly instead of disguising a seller pitch.";
const canonical = "/guides/downsizing-ad-seller-leads";

export const metadata: Metadata = { title, description, alternates: { canonical }, openGraph: { type: "article", title, description, url: canonical }, twitter: { card: "summary", title, description } };

const articleSchema = { "@context": "https://schema.org", "@type": "Article", headline: title, description, datePublished: "2026-07-24", dateModified: "2026-09-07", author: { "@type": "Organization", name: "Blockwise" }, publisher: { "@type": "Organization", name: "Blockwise", url: "https://blockwise.sale" }, mainEntityOfPage: `https://blockwise.sale${canonical}` };

const faqItems = [
  ["Is this deceptive if I want seller leads?", "It is transparent only when the ad offers a genuine buyer resource, delivers it, identifies the agent and explains the reason for follow-up. Ask about ownership and a possible sale in the conversation; do not hide a seller pitch behind a false registration."],
  ["What percentage of downsizer leads will be sellers?", "There is no universal percentage. Measure your own funnel: valid contacts, homeowners, seller conversations, appraisals and listings, with each rate using the preceding stage as its denominator."],
  ["What if there is little or no suitable stock?", "Do not publish a thin or fictional list. Pause, widen the clearly stated brief, use a waitlist only if you explain it, or choose another campaign angle."],
  ["How long should I track seller outcomes?", "Review quality and delivery after the first 14 days, then track the 90-day cohort for conversations, appraisals and listings. A click or form submission is not evidence of a shortened selling timeline."],
];

const adText = "See a current list of single-level, lower-maintenance homes in [Suburb]. The list shows price, location and features so you can compare your options. Request it here; the agent will explain what happens next.";

const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqItems.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };
export default function DownsizingAdGuidePage() {
  return <GuidesShell><ArticleProgress /><main id="main-content"><article className="bw-article">
    <header className="bw-article-hero"><div className="bw-article-hero-copy"><div className="bw-article-breadcrumbs"><Link href="/guides">Guides</Link><span aria-hidden>/</span><span>Seller leads</span></div><p className="bw-guides-label">The transparent test</p><h1>{title}</h1><p className="bw-article-deck">{description}</p><div className="bw-article-byline"><span>Blockwise</span><span>Updated 7 September 2026</span><span>6 minute read</span></div></div></header>
    <div className="bw-article-at-glance"><h2>At a glance</h2><dl><div><dt>Offer</dt><dd>A real list of lower-maintenance homes</dd></div><div><dt>Hypothesis</dt><dd>Some buyers already own and need to sell first</dd></div><div><dt>First review</dt><dd>Quality and delivery after 14 days</dd></div><div><dt>Cohort</dt><dd>Seller outcomes tracked for 90 days</dd></div><div><dt>Compliance</dt><dd>Consent, disclosure, agency and accessibility obligations</dd></div></dl></div>
    <div className="bw-article-body"><aside className="bw-article-toc" aria-label="On this page"><strong>On this page</strong><a href="#hypothesis">Hypothesis</a><a href="#offer">Offer and stock</a><a href="#campaign">Campaign</a><a href="#conversation">Qualification</a><a href="#economics">Economics</a><a href="#measure">Review windows</a></aside><div className="bw-article-prose">
      <section id="hypothesis" className="bw-opening"><p className="bw-drop-intro"><span>Start with a claim you can disprove.</span> A downsizer ad may attract people who value easier upkeep, accessible layouts, a different lifestyle or a smaller financial commitment. Some may already own a home and need to sell before buying. That is a hypothesis to test, not a hidden conversion trick.</p><p>The ad must be useful to the buyer even if they never sell. Say what is in the list, who the agent is and why you will follow up. Do not infer urgency from one click.</p></section>
      <section id="offer" className="bw-list-section"><div className="bw-section-heading"><span>Make the offer real</span><h2>Match the list to the life, not just the price.</h2><p>Check accessibility, stairs, garden and maintenance needs, proximity to services, pets, transport and lifestyle preferences. A lower price is only one possible reason to move.</p></div><div className="bw-list-grid"><div className="bw-list-item"><b>1</b><div><h3>Write the brief</h3><p>Example: single-level villas and compact homes with low garden upkeep near [Suburb] services.</p><span>Define terms people can verify</span></div></div><div className="bw-list-item"><b>2</b><div><h3>Check stock</h3><p>Record each matching property, source permission, current price and update date.</p><span>No stock means pause or revise the brief</span></div></div><div className="bw-list-item"><b>3</b><div><h3>Show the trade-offs</h3><p>Include strata, stairs, parking, renovation, distance and other material details where known.</p><span>“Low maintenance” is not “no maintenance”</span></div></div><div className="bw-list-item"><b>4</b><div><h3>Offer a next step</h3><p>Invite questions or a viewing. Ask about ownership only after delivering the buyer resource.</p><span>Buyer service first</span></div></div></div></section>
      <section className="bw-text-section"><h2>Synthetic matching-property list</h2><p>These rows are fictional teaching examples, not listings or market evidence.</p><div className="bw-measure-table" role="table" aria-label="Synthetic downsizer matching list"><div role="row" className="bw-measure-head"><span role="columnheader">Property</span><span role="columnheader">Price</span><span role="columnheader">Useful detail</span></div><div role="row"><span role="cell">Unit 3, Example Lane, [Suburb]</span><span role="cell">A$540,000</span><span role="cell">Single level; small courtyard; one step at entry (fictional)</span></div><div role="row"><span role="cell">8 Sample Road, [Suburb]</span><span role="cell">A$575,000</span><span role="cell">Compact garden; near bus route; strata fee to verify (fictional)</span></div><div role="row"><span role="cell">2 Placeholder Way, [Suburb]</span><span role="cell">A$610,000</span><span role="cell">Two bedrooms; no claim about accessibility until inspected (fictional)</span></div></div><a href="/guides/resources/downsizing-ad-seller-leads/synthetic-matching-property-list.csv" download>Download the synthetic matching-property list</a><p>If the list has no matching rows, do not replace it with “similar” properties without changing the ad. Choose a broader, clearly named brief, collect permission-based expressions of interest, or stop the test.</p></section>
      <section id="campaign" className="bw-campaign-section"><div className="bw-section-heading"><span>Campaign setup</span><h2>Test the buyer offer with a readable setup.</h2></div><div className="bw-campaign-settings"><dl><div><dt>Objective</dt><dd>Leads</dd></div><div><dt>Offer</dt><dd>Genuine lower-maintenance property list</dd></div><div><dt>Form</dt><dd>Full name and delivery email; mobile only when phone contact is explained</dd></div><div><dt>Budget example</dt><dd>A$20 daily for 14 days, with a named review date</dd></div><div><dt>Location</dt><dd>Use the account’s current compliant options; do not assume one Australian radius rule</dd></div></dl></div><GuideCopyBlock title="Buyer-facing ad copy" text={adText}/><GuideCopyBlock title="Buyer form copy" text="Full name; email; mobile (optional, only when phone purpose is explained and permitted). What would make a home easier for you to live in or maintain? [short answer]. Optional: Yes, send me occasional matching property updates from [Agency]. I can unsubscribe at any time."/><a href="/guides/resources/downsizing-ad-seller-leads/form-and-ad-copy.txt" download>Download the downsizer form and ad copy</a><p>Meta restrictions depend on account country and where the ad reaches. Special Ad Category rules may apply when an ad is based in the US or reaches the US, Canada or Europe. Check current requirements in the account. Nondiscrimination applies everywhere.</p></section>
      <section id="conversation" className="bw-creative-section"><div className="bw-section-heading"><span>Conversation scripts</span><h2>Ask clearly, then let the buyer choose.</h2></div><GuideCopyBlock title="First buyer call" text="Hi [name], it’s [agent] from [agency]. You requested the [list], so I’m checking that the link worked. What would make a home easier for you to live in or maintain? Would you like help comparing any of the options?"/><GuideCopyBlock title="Ownership question" text="To make sure I give you the right information: do you currently own a home, rent, or prefer not to say?"/><GuideCopyBlock title="Transparent transition" text="If you own, would you need to sell before buying, or are you exploring options only? I can explain the sale process if that is useful; there is no obligation and the list is still yours to use."/><p>Record “not ready”, “already represented”, “needs to sell”, “renting” or “prefer not to say”. Suppress future marketing when requested. Phone, email and SMS have different permission and compliance requirements.</p></section>
      <section id="economics"><DownsizingEconomicsCalculator /></section>
      <section id="measure" className="bw-measure-section"><div className="bw-section-heading"><span>Two review windows</span><h2>Separate early quality from later outcomes.</h2></div><div className="bw-contrast-row"><div><span>First 14 days</span><strong>Check that the ad, list, link, consent and contact details work. Review observed lead quality; do not call a result a trend without enough evidence.</strong></div><div><span>90-day cohort</span><strong>Keep the original cohort together and track homeowner answers, seller conversations, appraisals and listings. Record the dates and denominator at every step.</strong></div></div><a href="/guides/resources/downsizing-ad-seller-leads/downsize-funnel-tracker.csv" download>Download the cohort tracker CSV</a></section>
      <section className="bw-faq-section"><div className="bw-section-heading"><span>Questions</span><h2>The practical details.</h2></div>{faqItems.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
      <footer className="bw-article-sources"><h2>Sources</h2><ol><li><a href="https://developers.facebook.com/docs/marketing-api/audiences/special-ad-category/" target="_blank" rel="noreferrer">Meta Special Ad Category guidance</a></li><li><a href="https://www.acma.gov.au/avoid-sending-spam" target="_blank" rel="noreferrer">ACMA: Avoid sending spam</a></li><li><a href="https://www.oaic.gov.au/privacy/privacy-guidance-for-organisations-and-government-agencies/organisations/direct-marketing" target="_blank" rel="noreferrer">OAIC: Direct marketing</a></li></ol><p className="bw-last-reviewed">Updated 7 September 2026</p></footer>
    </div></div>
  </article></main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/></GuidesShell>;
}
