import { createCipheriv, createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { lstatSync, readFileSync } from "node:fs";
import { dirname, isAbsolute, resolve } from "node:path";
import { NextResponse } from "next/server";
import { createSupabaseServiceClient } from "@/lib/supabase/service";
import { readBoundedRequestBody, RequestBodyTooLargeError } from "@/lib/ops/request-body";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(request: Request) {
  let raw: string;
  try { raw = await readBoundedRequestBody(request, 128 * 1024); } catch (error) { return NextResponse.json({ error: error instanceof RequestBodyTooLargeError ? error.code : "request_body_unavailable" }, { status: 413 }); }
  let secret: string; try { secret=webhookSecret(); } catch { return NextResponse.json({ error: "webhook_not_configured" }, { status: 503 }); }
  const signature = request.headers.get("x-chatwoot-signature")?.trim() ?? ""; const timestamp = request.headers.get("x-chatwoot-timestamp")?.trim() ?? "";
  if (!signature || !timestamp || !/^\d+$/.test(timestamp) || Math.abs(Date.now() - Number(timestamp) * 1000) > 300000 || !verify(signature, timestamp, raw, secret)) return NextResponse.json({ error: "invalid_webhook_signature" }, { status: 401 });
  let body: Record<string, unknown>;
  try { const parsed=JSON.parse(raw); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error(); body=parsed as Record<string, unknown>; } catch { return NextResponse.json({ error: "invalid_webhook" }, { status: 422 }); }
  const eventType=typeof body.event === "string" ? body.event : ""; const conversation=record(body.conversation); const message=record(body.message);
  const conversationId=String(conversation?.id ?? body.conversation_id ?? ""); const messageId=String(message?.id ?? body.id ?? ""); const status=typeof conversation?.status === "string" ? conversation.status : (typeof body.status === "string" ? body.status : "");
  const inboxId=String(conversation?.inbox_id ?? body.inbox_id ?? ""); const meta=record(conversation?.meta) ?? record(body.meta); const sender=record(meta?.sender); const contact=record(conversation?.contact); const contactId=String(contact?.id ?? sender?.id ?? body.contact_id ?? "");
  const account=record(body.account); const accountId=String(account?.id ?? body.account_id ?? "");
  if (!/^\d+$/.test(conversationId) || !/^\d+$/.test(accountId) || !/^\d+$/.test(inboxId) || !/^\d+$/.test(contactId) || accountId !== (process.env.CHATWOOT_ACCOUNT_ID?.trim() ?? "") || inboxId !== (process.env.CHATWOOT_ENQUIRY_INBOX_ID?.trim() ?? "") || !["conversation_created","message_created","message_updated","conversation_status_changed","conversation_updated"].includes(eventType)) return NextResponse.json({ error: "unsupported_webhook" }, { status: 422 });
  const content=typeof body.content === "string" ? body.content.replace(/<[^>]*>/gu, " ").replace(/\s+/gu, " ").trim().slice(0,4000) : (typeof message?.content === "string" ? message.content.replace(/<[^>]*>/gu, " ").replace(/\s+/gu, " ").trim().slice(0,4000) : "");
  const occurredRaw=body.created_at ?? message?.created_at ?? conversation?.created_at; const occurredAt=typeof occurredRaw === "number" ? new Date(occurredRaw * 1000).toISOString() : (typeof occurredRaw === "string" && Number.isFinite(Date.parse(occurredRaw)) ? new Date(occurredRaw).toISOString() : new Date().toISOString());
  const senderDisplay=typeof sender?.name === "string" ? sender.name.trim().slice(0,256) : (typeof sender?.email === "string" ? sender.email.trim().slice(0,256) : null);
  const attachments=Array.isArray(body.attachments) ? body.attachments.slice(0,10).map((item) => { const value=record(item); return { name: typeof value?.file_name === "string" ? value.file_name.slice(0,128) : null, content_type: typeof value?.file_type === "string" ? value.file_type.slice(0,128) : null, size: typeof value?.file_size === "number" && value.file_size >= 0 && value.file_size <= 25_000_000 ? value.file_size : null }; }) : [];
  const rawMessageType=body.message_type ?? message?.message_type; const direction=typeof rawMessageType === "number" ? (rawMessageType === 0 ? "incoming" : "outgoing") : String(rawMessageType ?? "");
  if (eventType.startsWith("message_") && (body.private === true || message?.private === true || !["incoming","incoming_email"].includes(direction))) return NextResponse.json({ ok: true, status: "ignored" });
  const delivery=request.headers.get("x-chatwoot-delivery")?.trim() || createHash("sha256").update(`${timestamp}.${raw}`).digest("hex");
  const result=await createSupabaseServiceClient().rpc("record_ops_chatwoot_webhook_adopt", { p_event_id: delivery, p_payload_hash: createHash("sha256").update(raw).digest("hex"), p_account_id: accountId, p_inbox_id: inboxId, p_event_type: eventType, p_provider_conversation_id: conversationId, p_provider_message_id: messageId, p_contact_id_digest: createHash("sha256").update(contactId).digest("hex"), p_conversation_ciphertext: encryptConversationId(conversationId), p_status: status, p_body: content, p_occurred_at: occurredAt, p_sender_display: senderDisplay, p_attachments: attachments });
  if (result.error) return NextResponse.json({ error: "webhook_processing_failed" }, { status: 503 });
  return NextResponse.json({ ok: true, status: typeof result.data === "object" && result.data ? (result.data as Record<string, unknown>).status : "processed" });
}
function record(value: unknown): Record<string, unknown> | null { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : null; }
function verify(value: string, timestamp: string, raw: string, secret: string): boolean { if (!/^sha256=[0-9a-f]{64}$/iu.test(value)) return false; const expected=createHmac("sha256",secret).update(`${timestamp}.${raw}`).digest("hex"); return timingSafeEqual(Buffer.from(value.slice(7),"hex"),Buffer.from(expected,"hex")); }
function webhookSecret(): string { const path=process.env.CHATWOOT_WEBHOOK_SECRET_FILE?.trim(); if (!path || !isAbsolute(path)) throw new Error("CHATWOOT_WEBHOOK_SECRET_FILE is required"); const resolved=resolve(path); const stat=lstatSync(resolved); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error("CHATWOOT_WEBHOOK_SECRET_FILE is unsafe"); if (process.platform !== "win32") { if ((stat.mode & 0o777) !== 0o600 || (typeof process.getuid === "function" && stat.uid !== process.getuid())) throw new Error("CHATWOOT_WEBHOOK_SECRET_FILE has unsafe ownership or permissions"); let parent=dirname(resolved); while (parent && parent !== dirname(parent)) { const parentStat=lstatSync(parent); if (parentStat.isSymbolicLink() || (parentStat.mode & 0o022)) throw new Error("CHATWOOT_WEBHOOK_SECRET_FILE has unsafe path component"); parent=dirname(parent); } } const value=readFileSync(resolved,"utf8").trim(); if (!value) throw new Error("CHATWOOT_WEBHOOK_SECRET_FILE is empty"); return value; }
function encryptConversationId(value: string): string { const path=process.env.BLOCKWISE_OPS_CORRELATION_KEY_FILE?.trim(); if (!path || !isAbsolute(path)) throw new Error("BLOCKWISE_OPS_CORRELATION_KEY_FILE is required"); const resolved=resolve(path); const stat=lstatSync(resolved); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error("correlation key file is unsafe"); if (process.platform !== "win32" && ((stat.mode & 0o777) !== 0o600 || (typeof process.getuid === "function" && stat.uid !== process.getuid()))) throw new Error("correlation key file has unsafe permissions"); const key=createHash("sha256").update(readFileSync(resolved,"utf8").trim()).digest(); const iv=randomBytes(12); const cipher=createCipheriv("aes-256-gcm",key,iv); const encrypted=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]); return `v1:${iv.toString("base64url")}:${cipher.getAuthTag().toString("base64url")}:${encrypted.toString("base64url")}`; }
