import type { Metadata } from "next";
import Link from "next/link";

import { ArticleProgress } from "@/components/guides/article-progress";
import { GuideCopyBlock } from "@/components/guides/guide-copy-block";
import { GuidesShell } from "@/components/guides/guides-shell";

import "../guides.css";

const title = "Meta cannot optimise for listings if you only report leads";
const description = "A practical, privacy-aware guide to recording CRM outcomes, choosing an optimisation stage and returning compliant feedback through Meta’s Conversions API.";
const canonical = "/guides/meta-lead-quality-crm-feedback-loop";
const mappingCsv = `event_name,when,source,matching,consent_and_privacy
lead_received,form submitted,Meta lead form,Lead ID if available; otherwise supported click or customer-data match,record notice and purpose
contact_attempted,first outreach logged,CRM,Lead ID or approved fallback,limit access and retain only as needed
qualified_seller,objective criteria met,CRM,Lead ID recommended; follow Meta matching rules,document lawful basis and consent status
appraisal_booked,appointment confirmed,CRM,Lead ID recommended; fallback only when permitted,do not send free-text notes or secrets`;
const validationText = `CRM feedback validation checklist

[ ] Every lead is deduplicated and mapped to the correct ad account.
[ ] Lead ID is captured where available; it is recommended, not the only possible identifier.
[ ] Event names and timestamps come from the CRM record, not a guess.
[ ] Qualification rules are written, repeatable and reviewed for bias.
[ ] Consent, notice, access and retention rules are documented for the market.
[ ] Only approved fields are sent; never passwords, tokens, free-text notes or secrets.
[ ] Test events are visible in the selected dataset and errors are triaged.
[ ] Reconcile CRM counts with Meta diagnostics before choosing an optimisation stage.`;

export const metadata: Metadata = { title, description, alternates: { canonical }, openGraph: { type: "article", title, description, url: canonical, images: [{ url: "/guides/og-guides-index.webp", alt: "Blockwise real estate advertising guides" }] }, twitter: { card: "summary_large_image", title, description, images: ["/guides/og-guides-index.webp"] } };
const articleSchema = { "@context": "https://schema.org", "@type": "Article", headline: title, description, datePublished: "2026-07-24", dateModified: "2026-09-07", author: { "@type": "Organization", name: "Blockwise" }, publisher: { "@type": "Organization", name: "Blockwise", url: "https://blockwise.sale" }, mainEntityOfPage: `https://blockwise.sale${canonical}` };
const faq = [
  ["Do I need 200 leads per month?", "Meta’s 200-lead and 28-day, 1–40% conversion-rate guidance is a fit guideline for the conversion-leads goal, not a universal requirement. At lower volume, keep logging outcomes and measure the funnel internally; choose a stage only when the signal is reliable enough for your account."],
  ["Is the Meta Lead ID mandatory?", "No. Meta recommends the Lead ID because it directly links the CRM record to the lead form. Depending on the integration and current Meta requirements, approved click IDs or hashed email or phone matching may be alternatives. Verify the current documentation and avoid inventing a match."],
  ["Should I send every pipeline stage?", "Meta’s CRM integration guidance recommends sending stage updates, including the raw lead event, so the system has a complete signal. Separately, selecting an optimisation stage is a campaign decision: choose the downstream stage that is both valuable and frequent enough to learn from."],
  ["Does Blockwise connect my CRM for me?", "No. Blockwise can help keep lead review organised upstream. Your CRM connection, field mapping, privacy approvals and Meta setup remain external, gated work."],
];
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };

export default function LeadQualityGuidePage() {
  return <GuidesShell><ArticleProgress /><main id="main-content"><article className="bw-article">
    <header className="bw-article-hero"><div className="bw-article-hero-copy"><div className="bw-article-breadcrumbs"><Link href="/guides">Guides</Link><span aria-hidden>/</span><span>Lead quality</span></div><p className="bw-guides-label">The feedback loop guide</p><h1>{title}</h1><p className="bw-article-deck">A cheap form submission is not the same as a useful seller opportunity. Record what happens next, then decide which stage Meta should optimise toward.</p><div className="bw-article-byline"><span>By Blockwise</span><span>7 September 2026</span><span>6 minute read</span></div></div><div className="bw-article-hero-media" aria-label="Lead flow from form to CRM outcomes and feedback"><span>Lead received</span><span aria-hidden="true">→</span><span>CRM stages</span><span aria-hidden="true">→</span><span>Feedback</span></div></header>
    <div className="bw-article-body"><aside className="bw-article-toc" aria-label="On this page"><strong>On this page</strong><a href="#principle">The core distinction</a><a href="#stages">Record every stage</a><a href="#mapping">Worked mapping</a><a href="#fit">When the goal fits</a><a href="#validate">Validate and troubleshoot</a></aside><div className="bw-article-prose">
      <section className="bw-opening" id="principle"><p className="bw-drop-intro"><span>Meta needs the whole story.</span> The raw lead event is the start of the journey, not noise to discard. Meta’s CRM integration guidance recommends sending stage updates, including the raw lead, so reported outcomes form a coherent signal. That is different from the campaign choice of which stage to optimise toward.</p><div className="bw-contrast-row"><div><span>Report</span><strong>Send the lead and later stage updates you can support.</strong></div><div><span>Optimise</span><strong>Select one valuable, frequent stage for the campaign goal.</strong></div></div><aside className="bw-compliance-note"><strong>Housing and geography</strong><p>Meta’s published restrictions cover US-based advertisers and housing ads reaching the US, Canada or Europe. An Australian business advertising only in Australia is not automatically subject to those same audience restrictions; verify the current account controls and markets reached. Australia is not a universal radius or targeting rule. Check account country and current markets and apply nondiscrimination, consent and privacy controls for every market.</p><a href="https://developers.facebook.com/docs/marketing-api/conversions-api/conversion-leads-integration/crm-integration/3-implementing-the-crm-integration/" target="_blank" rel="noreferrer">Read Meta’s CRM implementation guidance →</a></aside></section>
      <section id="stages" className="bw-list-section"><div className="bw-section-heading bw-section-heading-split"><span>Build the record</span><h2>Report every meaningful stage you can verify.</h2><p>Do not collapse the journey into “lead” and “listing.” Consistent stage names make the internal report useful and give Meta the context its integration expects.</p></div><div className="bw-list-grid"><div className="bw-list-item"><b>1</b><div><h3>Lead received</h3><p>Store the form submission and source identifiers.</p><span>Event: lead_received · timestamp: form time</span></div></div><div className="bw-list-item"><b>2</b><div><h3>Contact and qualification</h3><p>Record attempted contact, owner confirmation and written criteria.</p><span>Events: contact_attempted, qualified_seller</span></div></div><div className="bw-list-item"><b>3</b><div><h3>Appointment and opportunity</h3><p>Record a confirmed appraisal, completed meeting or listing opportunity.</p><span>Events: appraisal_booked, listing_opportunity</span></div></div><div className="bw-list-item"><b>4</b><div><h3>Agreement outcome</h3><p>Record an agency agreement only when it actually exists.</p><span>Event: agency_agreement_signed</span></div></div></div></section>
      <section id="mapping" className="bw-text-section"><div className="bw-section-heading"><span>Platform-neutral example</span><h2>Map the CRM before touching the API.</h2></div><p>Use a mapping like this to agree what is sent, when it is sent and who can access it. Names are illustrative; check Meta’s current event and matching requirements in the integration you use.</p><div className="bw-measure-table" role="table" aria-label="CRM to Meta event mapping"><div role="row" className="bw-measure-head"><span role="columnheader">CRM change</span><span role="columnheader">Event</span><span role="columnheader">Time and match</span></div><div role="row"><strong role="cell">Form accepted</strong><span role="cell">lead_received</span><span role="cell">Form timestamp; Lead ID recommended</span></div><div role="row"><strong role="cell">Owner criteria met</strong><span role="cell">qualified_seller</span><span role="cell">Criteria timestamp; Lead ID or approved fallback</span></div><div role="row"><strong role="cell">Appointment confirmed</strong><span role="cell">appraisal_booked</span><span role="cell">Confirmation timestamp; approved match</span></div><div role="row"><strong role="cell">Agreement recorded</strong><span role="cell">agency_agreement_signed</span><span role="cell">Signed timestamp; approved match</span></div></div><p>Lead ID is recommended, not mandatory. Depending on the integration and current Meta rules, a click identifier or hashed email or phone may be accepted. Match only with documented permission and approved data handling; never send credentials, tokens or private notes.</p><GuideCopyBlock title="Copy the mapping CSV" text={mappingCsv} /><p><a href="/guides/resources/meta-lead-quality-crm-feedback-loop/crm-mapping.csv" download>Download crm-mapping.csv</a></p></section>
      <section id="fit" className="bw-measure-section"><div className="bw-section-heading"><span>Choose the learning signal</span><h2>Volume and timing are fit guidelines.</h2></div><p>Meta’s guidance commonly used for conversion-leads setup includes roughly 200 leads per month, a selected event within 28 days of lead generation and a 1–40% conversion rate. Treat these as practical fit guidelines, not a promise or a hard rule for every account.</p><div className="bw-contrast-row"><div><span>Higher volume</span><strong>Choose a valuable downstream stage that occurs often enough to learn from.</strong></div><div><span>Lower volume</span><strong>Keep every outcome in the CRM and use internal reporting while the sample grows.</strong></div></div><p>Reporting all stages does not mean optimising to the rarest stage. If signed agreements are too infrequent, an earlier, reliable stage may be the better optimisation choice.</p></section>
      <section id="validate" className="bw-followup-section"><div className="bw-section-heading"><span>Before launch and after</span><h2>Validate the loop, then diagnose gaps.</h2></div><ol><li>Confirm event names, timestamps, account and dataset mapping.</li><li>Send a controlled test and verify it appears in Meta diagnostics.</li><li>Compare CRM counts to received events; investigate duplicates, missing identifiers and delayed timestamps.</li><li>Check consent, privacy notice, access and retention; remove unapproved fields.</li><li>Wait for enough real data before changing the optimisation stage.</li></ol><GuideCopyBlock title="Copy the validation checklist" text={validationText} /><p><a href="/guides/resources/meta-lead-quality-crm-feedback-loop/validation-checklist.txt" download>Download validation-checklist.txt</a></p><p>For technical details, use Meta’s <a href="https://developers.facebook.com/documentation/ads-commerce/conversions-api/conversion-leads-integration" target="_blank" rel="noreferrer">Conversions API for CRM documentation</a>. Troubleshoot the data path first; do not solve a delivery problem by sending extra personal data.</p></section>
      <section className="bw-blockwise-cta"><div><span>Where Blockwise fits</span><h2>Keep every lead visible before feedback leaves the CRM.</h2><p>Blockwise can help organise incoming Meta leads in an upstream review path. The CRM connection, matching configuration, privacy approvals and Meta optimisation choice remain external.</p></div><Link href="/signup">Organise lead review <span aria-hidden="true">→</span></Link></section>
      <section className="bw-faq-section"><div className="bw-section-heading"><span>Questions</span><h2>The practical details.</h2></div>{faq.map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
      <footer className="bw-article-sources"><h2>Sources and further reading</h2><ol><li><a href="https://developers.facebook.com/docs/marketing-api/conversions-api/conversion-leads-integration/crm-integration/3-implementing-the-crm-integration/" target="_blank" rel="noreferrer">Implement the CRM integration, Meta for Developers</a></li><li><a href="https://developers.facebook.com/documentation/ads-commerce/conversions-api/conversion-leads-integration" target="_blank" rel="noreferrer">Conversions API for CRM, Meta for Developers</a></li><li><a href="https://www.facebook.com/business/generate-leads/conversions-api-for-crm" target="_blank" rel="noreferrer">Improve lead quality with Conversions API for CRM, Meta for Business</a></li><li><a href="https://developers.facebook.com/docs/marketing-api/audiences/special-ad-category/" target="_blank" rel="noreferrer">Special Ad Category, Meta for Developers</a></li></ol></footer>
    </div></div>
  </article></main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /></GuidesShell>;
}
