create table research.source_fetch_log (
    id bigint generated by default as identity primary key,
    index_source_url text not null,
    fetched_at timestamp with time zone default now(),
    rows_found integer not null,
    notes text
);

create index source_fetch_log_index_source_url_idx on research.source_fetch_log(index_source_url);
create index source_fetch_log_fetched_at_idx on research.source_fetch_log(fetched_at);