create table research.target_manifest (
    id bigint generated by default as identity primary key,
    instrument_name text not null,
    category text not null,
    issuing_authority text not null,
    index_source_url text not null,
    canonical_url text not null,
    expected_version_hint text,
    status text not null check (status in ('pending', 'acquired', 'metadata_only', 'blocked', 'out_of_scope')),
    source_document_id uuid references research.source_documents(id),
    last_checked_at timestamp with time zone,
    notes text
);

create index target_manifest_status_idx on research.target_manifest(status);
create index target_manifest_source_document_id_idx on research.target_manifest(source_document_id);